### PR TITLE
Handle hyphens in function names

### PR DESCRIPTION
**Pull request by zmk-punchbowl**
In our `serverless.yml`, we use hyphens (`-`) in our function names (for example `note-get`, and `note-create`) and this is a legal convention in Serverless. However, we could not use this plugin to document our API because of this (since `-` is not legally allowed in a Typescript namespace). 

This PR adjusts the way function names are converted to namespace names using `camelCase` from `lodash`. For example, `note-get` becomes `noteGet` and `note_create-multiple` would become `noteCreateMultiple`. 

I also added a basic test for this (mostly relying on an existing test). Hopefully this helps. Thanks for creating a useful plugin.

Note that in our own usage, I could not get the plugin working with `@conqa/serverless-openapi-documentation` and had to swap it out for `@martinsson/serverless-openapi-documentation`, but since that seems to be unrelated to this issue, I left that in a separate branch for now.

### CODE REVIEW

**Comment by roni-frantchi** [comment]
Hey @zmk-punchbowl thanks so much for this contribution! ❤️  
Both implementation and test added looks great to me.  
Would you mind also adding a note on our [README](https://github.com/env0/serverless-openapi-typescript/blob/main/README.md) ?  

> I could not get the plugin working with @conqa/serverless-openapi-documentation and had to swap it out for @martinsson/serverless-openapi-documentation

If you could open a separate issue with some more details as to the error/versions used/anything we can use to recreate we'd be happy to look at it.  

Thanks!

**Comment by zmk-punchbowl** [comment]
> Hey @zmk-punchbowl thanks so much for this contribution! ❤️ Both implementation and test added looks great to me. Would you mind also adding a note on our [README](https://github.com/env0/serverless-openapi-typescript/blob/main/README.md) ?
> 
> > I could not get the plugin working with @conqa/serverless-openapi-documentation and had to swap it out for @martinsson/serverless-openapi-documentation
> 
> If you could open a separate issue with some more details as to the error/versions used/anything we can use to recreate we'd be happy to look at it.
> 
> Thanks!

Thanks @roni-frantchi. I've made an update to the README that is hopefully acceptable.

I've moved onto another development priority at the moment, so unfortunately, I'm not sure when I'll be able to repro & document the issue I had with the plugin dependency. If it's working well for you guys, then it may just be in my environment.

**Review by roni-frantchi — APPROVED** [review]
@zmk-punchbowl sorry for taking so long.

**Comment by zmk-punchbowl** [comment]
> @zmk-punchbowl sorry for taking so long.

No problem! Thanks for maintaining this useful package.

**Pull request merged**
